#!/usr/bin/env python3
"""One-off generator for Prompt 50 content .tres files (run from repo root)."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BD = ROOT / "resources/building_data"
ED = ROOT / "resources/enemy_data"
AD = ROOT / "resources/ally_data"
RD = ROOT / "resources/research_data"

SCRIPT_BD = 'res://scripts/resources/building_data.gd'
SCRIPT_ED = 'res://scripts/resources/enemy_data.gd'
SCRIPT_AD = 'res://scripts/resources/ally_data.gd'
SCRIPT_RN = 'res://scripts/resources/research_node_data.gd'
PROJ = 'res://scenes/projectiles/projectile_base.tscn'


def wbd(name: str, bt: int, lines: list[str], with_proj: bool = True) -> None:
    ls = 3 if with_proj else 2
    out = [
        f'[gd_resource type="Resource" script_class="BuildingData" load_steps={ls} format=3]',
        "",
        f'[ext_resource type="Script" path="{SCRIPT_BD}" id="1_buildingdata"]',
    ]
    if with_proj:
        out.append(f'[ext_resource type="PackedScene" path="{PROJ}" id="2_projectile"]')
    out.append("")
    out.append("[resource]")
    out.append('script = ExtResource("1_buildingdata")')
    out.extend(lines)
    if with_proj:
        out.append('projectile_scene = ExtResource("2_projectile")')
    out.append("")
    (BD / name).write_text("\n".join(out))


def wed(name: str, lines: list[str]) -> None:
    out = [
        '[gd_resource type="Resource" script_class="EnemyData" load_steps=2 format=3]',
        "",
        f'[ext_resource type="Script" path="{SCRIPT_ED}" id="1"]',
        "",
        "[resource]",
        'script = ExtResource("1")',
    ]
    out.extend(lines)
    out.append("")
    (ED / name).write_text("\n".join(out))


def ally(name: str, lines: list[str]) -> None:
    out = [
        '[gd_resource type="Resource" script_class="AllyData" load_steps=2 format=3]',
        "",
        f'[ext_resource type="Script" path="{SCRIPT_AD}" id="1"]',
        "",
        "[resource]",
        'script = ExtResource("1")',
    ]
    out.extend(lines)
    out.append("")
    (AD / name).write_text("\n".join(out))


def rnode(name: str, node_id: str, disp: str, cost: int, prereqs: list[str], desc: str) -> None:
    pre = "[]" if not prereqs else "[" + ", ".join(f'"{p}"' for p in prereqs) + "]"
    out = [
        '[gd_resource type="Resource" script_class="ResearchNodeData" format=3]',
        "",
        f'[ext_resource type="Script" path="{SCRIPT_RN}" id="1_researchnodedata"]',
        "",
        "[resource]",
        'script = ExtResource("1_researchnodedata")',
        f'node_id = "{node_id}"',
        f'display_name = "{disp}"',
        f"research_cost = {cost}",
        f"prerequisite_ids = {pre}",
        f'description = "{desc}"',
        "",
    ]
    (RD / name).write_text("\n".join(out))


# --- New buildings (28) ---
wbd(
    "spike_spitter.tres",
    8,
    [
        'building_id = "spike_spitter"',
        "building_type = 8",
        'display_name = "Spike Spitter"',
        "gold_cost = 40",
        "material_cost = 1",
        "upgrade_gold_cost = 24",
        "upgrade_material_cost = 1",
        "damage = 18.0",
        "upgraded_damage = 22.0",
        "fire_rate = 1.2",
        "attack_range = 13.0",
        "upgraded_range = 15.0",
        "damage_type = 0",
        "targets_air = false",
        "targets_ground = true",
        "is_locked = false",
        "unlock_research_id = \"unlock_spike_spitter\"",
        "color = Color(0.6, 0.5, 0.3, 1.0)",
        "footprint_size_class = 0",
        'size_class = "SMALL"',
        'role_tags = Array[String](["DPS"])',
        'balance_status = "UNTESTED"',
    ],
)

wbd(
    "ember_vent.tres",
    9,
    [
        'building_id = "ember_vent"',
        "building_type = 9",
        'display_name = "Ember Vent"',
        "gold_cost = 45",
        "material_cost = 1",
        "upgrade_gold_cost = 27",
        "upgrade_material_cost = 1",
        "damage = 8.0",
        "upgraded_damage = 14.0",
        "fire_rate = 1.0",
        "attack_range = 11.0",
        "upgraded_range = 12.0",
        "damage_type = 1",
        "targets_air = false",
        "targets_ground = true",
        "is_locked = false",
        'unlock_research_id = "unlock_frost_pinger"',
        "color = Color(1.0, 0.4, 0.0, 1.0)",
        "dot_enabled = true",
        "dot_total_damage = 12.0",
        "dot_tick_interval = 1.0",
        "dot_duration = 3.0",
        'dot_effect_type = "burn"',
        'dot_source_id = "ember_vent"',
        "dot_in_addition_to_hit = true",
        "footprint_size_class = 0",
        'size_class = "SMALL"',
        'role_tags = Array[String](["DPS"])',
        'balance_status = "UNTESTED"',
    ],
)

wbd(
    "frost_pinger.tres",
    10,
    [
        'building_id = "frost_pinger"',
        "building_type = 10",
        'display_name = "Frost Pinger"',
        "gold_cost = 50",
        "material_cost = 1",
        "upgrade_gold_cost = 30",
        "upgrade_material_cost = 1",
        "damage = 12.0",
        "upgraded_damage = 20.0",
        "fire_rate = 0.8",
        "attack_range = 14.0",
        "upgraded_range = 16.0",
        "damage_type = 2",
        "targets_air = false",
        "targets_ground = true",
        "is_locked = false",
        'unlock_research_id = "unlock_frost_pinger"',
        "color = Color(0.4, 0.7, 1.0, 1.0)",
        "footprint_size_class = 0",
        'size_class = "SMALL"',
        'role_tags = Array[String](["DPS", "SUPPORT"])',
        'balance_status = "UNTESTED"',
    ],
)

wbd(
    "netgun.tres",
    11,
    [
        'building_id = "netgun"',
        "building_type = 11",
        'display_name = "Net Gun"',
        "gold_cost = 35",
        "material_cost = 0",
        "upgrade_gold_cost = 21",
        "upgrade_material_cost = 0",
        "damage = 6.0",
        "upgraded_damage = 10.0",
        "fire_rate = 0.6",
        "attack_range = 12.0",
        "upgraded_range = 14.0",
        "damage_type = 0",
        "targets_air = false",
        "targets_ground = true",
        "is_locked = false",
        'unlock_research_id = ""',
        "color = Color(0.5, 0.5, 0.5, 1.0)",
        "footprint_size_class = 0",
        'size_class = "SMALL"',
        'role_tags = Array[String](["DPS", "SUPPORT"])',
        'balance_status = "UNTESTED"',
    ],
)

wbd(
    "acid_dripper.tres",
    12,
    [
        'building_id = "acid_dripper"',
        "building_type = 12",
        'display_name = "Acid Dripper"',
        "gold_cost = 40",
        "material_cost = 1",
        "upgrade_gold_cost = 24",
        "upgrade_material_cost = 1",
        "damage = 5.0",
        "upgraded_damage = 9.0",
        "fire_rate = 1.5",
        "attack_range = 10.0",
        "upgraded_range = 11.0",
        "damage_type = 3",
        "targets_air = false",
        "targets_ground = true",
        "is_locked = false",
        'unlock_research_id = ""',
        "color = Color(0.3, 0.8, 0.1, 1.0)",
        "dot_enabled = true",
        "dot_total_damage = 15.0",
        "dot_tick_interval = 1.0",
        "dot_duration = 4.0",
        'dot_effect_type = "acid"',
        'dot_source_id = "acid_dripper"',
        "dot_in_addition_to_hit = true",
        "footprint_size_class = 0",
        'size_class = "SMALL"',
        'role_tags = Array[String](["DPS"])',
        'balance_status = "UNTESTED"',
    ],
)

wbd(
    "wolfden.tres",
    13,
    [
        'building_id = "wolfden"',
        "building_type = 13",
        'display_name = "Wolf Den"',
        "gold_cost = 55",
        "material_cost = 1",
        "upgrade_gold_cost = 33",
        "upgrade_material_cost = 1",
        "damage = 0.0",
        "upgraded_damage = 0.0",
        "fire_rate = 0.0",
        "attack_range = 0.0",
        "upgraded_range = 0.0",
        "damage_type = 0",
        "targets_air = false",
        "targets_ground = true",
        "is_locked = false",
        'unlock_research_id = "unlock_wolfden"',
        "color = Color(0.6, 0.4, 0.2, 1.0)",
        "is_summoner = true",
        "summon_squad_size = 2",
        'summon_leader_data_path = "res://resources/ally_data/wolf_alpha.tres"',
        'summon_follower_data_path = "res://resources/ally_data/wolf_pup.tres"',
        "summon_cooldown = 12.0",
        'summon_respawn_type = "mortal"',
        "summon_respawn_delay = 8.0",
        "summon_is_blocker = true",
        "footprint_size_class = 0",
        'size_class = "SMALL"',
        'role_tags = Array[String](["SUMMONER", "BLOCKER"])',
        'balance_status = "UNTESTED"',
    ],
    with_proj=False,
)

wbd(
    "crow_roost.tres",
    14,
    [
        'building_id = "crow_roost"',
        "building_type = 14",
        'display_name = "Crow Roost"',
        "gold_cost = 45",
        "material_cost = 1",
        "upgrade_gold_cost = 27",
        "upgrade_material_cost = 1",
        "damage = 14.0",
        "upgraded_damage = 22.0",
        "fire_rate = 1.4",
        "attack_range = 18.0",
        "upgraded_range = 20.0",
        "damage_type = 0",
        "targets_air = true",
        "targets_ground = false",
        "is_locked = false",
        'unlock_research_id = "unlock_crow_roost"',
        "color = Color(0.2, 0.2, 0.3, 1.0)",
        "footprint_size_class = 0",
        'size_class = "SMALL"',
        'role_tags = Array[String](["DPS", "AA"])',
        'balance_status = "UNTESTED"',
    ],
)

wbd(
    "alarm_totems.tres",
    15,
    [
        'building_id = "alarm_totems"',
        "building_type = 15",
        'display_name = "Alarm Totems"',
        "gold_cost = 40",
        "material_cost = 1",
        "damage = 0.0",
        "fire_rate = 0.0",
        "attack_range = 0.0",
        "upgraded_range = 0.0",
        "damage_type = 0",
        "targets_air = false",
        "targets_ground = true",
        "is_locked = false",
        'unlock_research_id = ""',
        "color = Color(0.8, 0.7, 0.2, 1.0)",
        "is_aura = true",
        'aura_category = "enemy_slow"',
        "aura_radius = 6.0",
        'aura_effect_type = "enemy_speed_pct"',
        "aura_effect_value = -0.20",
        "footprint_size_class = 0",
        'size_class = "SMALL"',
        'role_tags = Array[String](["AURA", "SUPPORT"])',
        'balance_status = "UNTESTED"',
    ],
    with_proj=False,
)

wbd(
    "crossfire_nest.tres",
    16,
    [
        'building_id = "crossfire_nest"',
        "building_type = 16",
        'display_name = "Crossfire Nest"',
        "gold_cost = 50",
        "material_cost = 1",
        "upgrade_gold_cost = 30",
        "upgrade_material_cost = 1",
        "damage = 10.0",
        "upgraded_damage = 16.0",
        "fire_rate = 1.0",
        "attack_range = 15.0",
        "upgraded_range = 17.0",
        "damage_type = 0",
        "targets_air = true",
        "targets_ground = true",
        "is_locked = false",
        'unlock_research_id = ""',
        "color = Color(0.7, 0.6, 0.2, 1.0)",
        "footprint_size_class = 0",
        'size_class = "SMALL"',
        'role_tags = Array[String](["DPS", "AA"])',
        'balance_status = "UNTESTED"',
    ],
)

wbd(
    "bolt_shrine.tres",
    17,
    [
        'building_id = "bolt_shrine"',
        "building_type = 17",
        'display_name = "Bolt Shrine"',
        "gold_cost = 45",
        "material_cost = 1",
        "upgrade_gold_cost = 27",
        "upgrade_material_cost = 1",
        "damage = 20.0",
        "upgraded_damage = 32.0",
        "fire_rate = 0.33",
        "attack_range = 12.0",
        "upgraded_range = 13.0",
        "damage_type = 2",
        "targets_air = false",
        "targets_ground = true",
        "is_locked = false",
        'unlock_research_id = ""',
        "color = Color(0.5, 0.2, 0.9, 1.0)",
        "footprint_size_class = 0",
        'size_class = "SMALL"',
        'role_tags = Array[String](["DPS"])',
        'balance_status = "UNTESTED"',
    ],
)

wbd(
    "thornwall.tres",
    18,
    [
        'building_id = "thornwall"',
        "building_type = 18",
        'display_name = "Thornwall"',
        "gold_cost = 30",
        "material_cost = 0",
        "upgrade_gold_cost = 18",
        "upgrade_material_cost = 0",
        "damage = 8.0",
        "upgraded_damage = 14.0",
        "fire_rate = 0.5",
        "attack_range = 4.0",
        "upgraded_range = 4.0",
        "damage_type = 0",
        "targets_air = false",
        "targets_ground = true",
        "is_locked = false",
        'unlock_research_id = ""',
        "color = Color(0.3, 0.6, 0.1, 1.0)",
        "footprint_size_class = 0",
        'size_class = "SMALL"',
        'role_tags = Array[String](["DPS", "BLOCKER"])',
        'balance_status = "UNTESTED"',
    ],
)

wbd(
    "field_medic.tres",
    19,
    [
        'building_id = "field_medic"',
        "building_type = 19",
        'display_name = "Field Medic"',
        "gold_cost = 50",
        "material_cost = 1",
        "damage = 0.0",
        "fire_rate = 0.0",
        "attack_range = 0.0",
        "upgraded_range = 0.0",
        "damage_type = 0",
        "targets_air = false",
        "targets_ground = true",
        "is_locked = false",
        'unlock_research_id = ""',
        "color = Color(0.8, 0.9, 0.8, 1.0)",
        "is_healer = true",
        "heal_per_tick = 8.0",
        "heal_tick_interval = 2.0",
        "heal_radius = 8.0",
        'heal_targets = "allies"',
        "footprint_size_class = 0",
        'size_class = "SMALL"',
        'role_tags = Array[String](["HEALER"])',
        'balance_status = "UNTESTED"',
    ],
    with_proj=False,
)

# Medium 20-29
wbd(
    "greatbow_turret.tres",
    20,
    [
        'building_id = "greatbow_turret"',
        "building_type = 20",
        'display_name = "Greatbow Turret"',
        "gold_cost = 100",
        "material_cost = 3",
        "upgrade_gold_cost = 60",
        "upgrade_material_cost = 2",
        "damage = 35.0",
        "upgraded_damage = 55.0",
        "fire_rate = 0.7",
        "attack_range = 22.0",
        "upgraded_range = 25.0",
        "damage_type = 0",
        "targets_air = false",
        "targets_ground = true",
        "is_locked = false",
        'unlock_research_id = "unlock_greatbow_turret"',
        "color = Color(0.7, 0.5, 0.3, 1.0)",
        "footprint_size_class = 0",
        'size_class = "MEDIUM"',
        'role_tags = Array[String](["DPS"])',
        'balance_status = "UNTESTED"',
    ],
)

wbd(
    "molten_caster.tres",
    21,
    [
        'building_id = "molten_caster"',
        "building_type = 21",
        'display_name = "Molten Caster"',
        "gold_cost = 120",
        "material_cost = 3",
        "upgrade_gold_cost = 72",
        "upgrade_material_cost = 2",
        "damage = 28.0",
        "upgraded_damage = 45.0",
        "fire_rate = 0.6",
        "attack_range = 16.0",
        "upgraded_range = 18.0",
        "damage_type = 1",
        "targets_air = false",
        "targets_ground = true",
        "is_locked = false",
        'unlock_research_id = "unlock_molten_caster"',
        "color = Color(1.0, 0.3, 0.0, 1.0)",
        "dot_enabled = true",
        "dot_total_damage = 20.0",
        "dot_tick_interval = 1.0",
        "dot_duration = 4.0",
        'dot_effect_type = "burn"',
        'dot_source_id = "molten_caster"',
        "dot_in_addition_to_hit = true",
        "footprint_size_class = 0",
        'size_class = "MEDIUM"',
        'role_tags = Array[String](["DPS", "ARTILLERY"])',
        'balance_status = "UNTESTED"',
    ],
)

wbd(
    "arcane_lens.tres",
    22,
    [
        'building_id = "arcane_lens"',
        "building_type = 22",
        'display_name = "Arcane Lens"',
        "gold_cost = 130",
        "material_cost = 4",
        "upgrade_gold_cost = 78",
        "upgrade_material_cost = 2",
        "damage = 30.0",
        "upgraded_damage = 48.0",
        "fire_rate = 0.9",
        "attack_range = 20.0",
        "upgraded_range = 22.0",
        "damage_type = 2",
        "targets_air = false",
        "targets_ground = true",
        "is_locked = false",
        'unlock_research_id = "unlock_arcane_lens"',
        "color = Color(0.4, 0.0, 0.8, 1.0)",
        "footprint_size_class = 0",
        'size_class = "MEDIUM"',
        'role_tags = Array[String](["DPS"])',
        'balance_status = "UNTESTED"',
    ],
)

wbd(
    "plague_mortar.tres",
    23,
    [
        'building_id = "plague_mortar"',
        "building_type = 23",
        'display_name = "Plague Mortar"',
        "gold_cost = 110",
        "material_cost = 3",
        "upgrade_gold_cost = 66",
        "upgrade_material_cost = 2",
        "damage = 18.0",
        "upgraded_damage = 30.0",
        "fire_rate = 0.5",
        "attack_range = 24.0",
        "upgraded_range = 26.0",
        "damage_type = 3",
        "targets_air = false",
        "targets_ground = true",
        "is_locked = false",
        'unlock_research_id = ""',
        "color = Color(0.2, 0.6, 0.1, 1.0)",
        "dot_enabled = true",
        "dot_total_damage = 25.0",
        "dot_tick_interval = 1.0",
        "dot_duration = 5.0",
        'dot_effect_type = "poison"',
        'dot_source_id = "plague_mortar"',
        "dot_in_addition_to_hit = false",
        "footprint_size_class = 0",
        'size_class = "MEDIUM"',
        'role_tags = Array[String](["DPS", "ARTILLERY"])',
        'balance_status = "UNTESTED"',
    ],
)

wbd(
    "bear_den.tres",
    24,
    [
        'building_id = "bear_den"',
        "building_type = 24",
        'display_name = "Bear Den"',
        "gold_cost = 130",
        "material_cost = 4",
        "upgrade_gold_cost = 78",
        "upgrade_material_cost = 2",
        "damage = 0.0",
        "upgraded_damage = 0.0",
        "fire_rate = 0.0",
        "attack_range = 0.0",
        "upgraded_range = 0.0",
        "damage_type = 0",
        "targets_air = false",
        "targets_ground = true",
        "is_locked = false",
        'unlock_research_id = "unlock_bear_den"',
        "color = Color(0.5, 0.3, 0.1, 1.0)",
        "is_summoner = true",
        "summon_squad_size = 2",
        'summon_leader_data_path = "res://resources/ally_data/bear_alpha.tres"',
        'summon_follower_data_path = "res://resources/ally_data/wolf_alpha.tres"',
        "summon_cooldown = 18.0",
        'summon_respawn_type = "mortal"',
        "summon_respawn_delay = 10.0",
        "summon_is_blocker = true",
        "footprint_size_class = 0",
        'size_class = "MEDIUM"',
        'role_tags = Array[String](["SUMMONER", "BLOCKER"])',
        'balance_status = "UNTESTED"',
    ],
    with_proj=False,
)

wbd(
    "gust_cannon.tres",
    25,
    [
        'building_id = "gust_cannon"',
        "building_type = 25",
        'display_name = "Gust Cannon"',
        "gold_cost = 110",
        "material_cost = 3",
        "upgrade_gold_cost = 66",
        "upgrade_material_cost = 2",
        "damage = 22.0",
        "upgraded_damage = 35.0",
        "fire_rate = 1.0",
        "attack_range = 20.0",
        "upgraded_range = 22.0",
        "damage_type = 0",
        "targets_air = true",
        "targets_ground = true",
        "is_locked = false",
        'unlock_research_id = "unlock_gust_cannon"',
        "color = Color(0.6, 0.8, 1.0, 1.0)",
        "footprint_size_class = 0",
        'size_class = "MEDIUM"',
        'role_tags = Array[String](["DPS", "AA"])',
        'balance_status = "UNTESTED"',
    ],
)

wbd(
    "warden_shrine.tres",
    26,
    [
        'building_id = "warden_shrine"',
        "building_type = 26",
        'display_name = "Warden Shrine"',
        "gold_cost = 120",
        "material_cost = 4",
        "damage = 0.0",
        "fire_rate = 0.0",
        "attack_range = 0.0",
        "upgraded_range = 0.0",
        "damage_type = 0",
        "targets_air = false",
        "targets_ground = true",
        "is_locked = false",
        'unlock_research_id = "unlock_warden_shrine"',
        "color = Color(1.0, 0.85, 0.2, 1.0)",
        "is_aura = true",
        'aura_category = "damage_flat"',
        "aura_radius = 12.0",
        'aura_effect_type = "damage_pct"',
        "aura_effect_value = 0.15",
        "footprint_size_class = 0",
        'size_class = "MEDIUM"',
        'role_tags = Array[String](["AURA", "SUPPORT"])',
        'balance_status = "UNTESTED"',
    ],
    with_proj=False,
)

wbd(
    "iron_cleric.tres",
    27,
    [
        'building_id = "iron_cleric"',
        "building_type = 27",
        'display_name = "Iron Cleric"',
        "gold_cost = 120",
        "material_cost = 3",
        "damage = 0.0",
        "fire_rate = 0.0",
        "attack_range = 0.0",
        "upgraded_range = 0.0",
        "damage_type = 0",
        "targets_air = false",
        "targets_ground = true",
        "is_locked = false",
        'unlock_research_id = ""',
        "color = Color(0.9, 0.9, 0.7, 1.0)",
        "is_healer = true",
        "heal_per_tick = 15.0",
        "heal_tick_interval = 2.0",
        "heal_radius = 14.0",
        'heal_targets = "buildings"',
        "footprint_size_class = 0",
        'size_class = "MEDIUM"',
        'role_tags = Array[String](["HEALER"])',
        'balance_status = "UNTESTED"',
    ],
    with_proj=False,
)

wbd(
    "siege_ballista.tres",
    28,
    [
        'building_id = "siege_ballista"',
        "building_type = 28",
        'display_name = "Siege Ballista"',
        "gold_cost = 140",
        "material_cost = 4",
        "upgrade_gold_cost = 84",
        "upgrade_material_cost = 3",
        "damage = 50.0",
        "upgraded_damage = 80.0",
        "fire_rate = 0.4",
        "attack_range = 28.0",
        "upgraded_range = 32.0",
        "damage_type = 0",
        "targets_air = false",
        "targets_ground = true",
        "is_locked = true",
        'unlock_research_id = "unlock_siege_ballista"',
        "color = Color(0.6, 0.4, 0.2, 1.0)",
        "footprint_size_class = 0",
        'size_class = "MEDIUM"',
        'role_tags = Array[String](["DPS", "ARTILLERY"])',
        'balance_status = "UNTESTED"',
    ],
)

wbd(
    "chain_lightning.tres",
    29,
    [
        'building_id = "chain_lightning"',
        "building_type = 29",
        'display_name = "Chain Lightning"',
        "gold_cost = 130",
        "material_cost = 4",
        "upgrade_gold_cost = 78",
        "upgrade_material_cost = 2",
        "damage = 25.0",
        "upgraded_damage = 40.0",
        "fire_rate = 1.1",
        "attack_range = 20.0",
        "upgraded_range = 22.0",
        "damage_type = 2",
        "targets_air = true",
        "targets_ground = true",
        "is_locked = true",
        'unlock_research_id = "unlock_chain_lightning"',
        "color = Color(0.6, 0.8, 1.0, 1.0)",
        "footprint_size_class = 0",
        'size_class = "MEDIUM"',
        'role_tags = Array[String](["DPS", "AA"])',
        'balance_status = "UNTESTED"',
    ],
)

# Large 30-35
wbd(
    "fortress_cannon.tres",
    30,
    [
        'building_id = "fortress_cannon"',
        "building_type = 30",
        'display_name = "Fortress Cannon"',
        "gold_cost = 280",
        "material_cost = 7",
        "upgrade_gold_cost = 168",
        "upgrade_material_cost = 4",
        "damage = 90.0",
        "upgraded_damage = 140.0",
        "fire_rate = 0.5",
        "attack_range = 26.0",
        "upgraded_range = 28.0",
        "damage_type = 0",
        "targets_air = false",
        "targets_ground = true",
        "is_locked = true",
        'unlock_research_id = "unlock_fortress_cannon"',
        "color = Color(0.5, 0.5, 0.4, 1.0)",
        "footprint_size_class = 0",
        'size_class = "LARGE"',
        'role_tags = Array[String](["DPS", "ARTILLERY"])',
        'balance_status = "UNTESTED"',
    ],
)

wbd(
    "dragon_forge.tres",
    31,
    [
        'building_id = "dragon_forge"',
        "building_type = 31",
        'display_name = "Dragon Forge"',
        "gold_cost = 350",
        "material_cost = 8",
        "upgrade_gold_cost = 210",
        "upgrade_material_cost = 5",
        "damage = 70.0",
        "upgraded_damage = 110.0",
        "fire_rate = 0.6",
        "attack_range = 22.0",
        "upgraded_range = 24.0",
        "damage_type = 1",
        "targets_air = false",
        "targets_ground = true",
        "is_locked = true",
        'unlock_research_id = "unlock_dragon_forge"',
        "color = Color(1.0, 0.2, 0.0, 1.0)",
        "dot_enabled = true",
        "dot_total_damage = 40.0",
        "dot_tick_interval = 1.0",
        "dot_duration = 5.0",
        'dot_effect_type = "burn"',
        'dot_source_id = "dragon_forge"',
        "dot_in_addition_to_hit = true",
        "footprint_size_class = 0",
        'size_class = "LARGE"',
        'role_tags = Array[String](["DPS", "ARTILLERY"])',
        'balance_status = "UNTESTED"',
    ],
)

wbd(
    "void_obelisk.tres",
    32,
    [
        'building_id = "void_obelisk"',
        "building_type = 32",
        'display_name = "Void Obelisk"',
        "gold_cost = 300",
        "material_cost = 8",
        "upgrade_gold_cost = 180",
        "upgrade_material_cost = 5",
        "damage = 60.0",
        "upgraded_damage = 95.0",
        "fire_rate = 0.8",
        "attack_range = 24.0",
        "upgraded_range = 26.0",
        "damage_type = 2",
        "targets_air = false",
        "targets_ground = true",
        "is_locked = true",
        'unlock_research_id = "unlock_void_obelisk"',
        "color = Color(0.2, 0.0, 0.5, 1.0)",
        "footprint_size_class = 0",
        'size_class = "LARGE"',
        'role_tags = Array[String](["DPS", "SUPPORT"])',
        'balance_status = "UNTESTED"',
    ],
)

wbd(
    "plague_cauldron.tres",
    33,
    [
        'building_id = "plague_cauldron"',
        "building_type = 33",
        'display_name = "Plague Cauldron"',
        "gold_cost = 280",
        "material_cost = 7",
        "upgrade_gold_cost = 168",
        "upgrade_material_cost = 4",
        "damage = 30.0",
        "upgraded_damage = 48.0",
        "fire_rate = 1.0",
        "attack_range = 20.0",
        "upgraded_range = 22.0",
        "damage_type = 3",
        "targets_air = false",
        "targets_ground = true",
        "is_locked = true",
        'unlock_research_id = "unlock_plague_cauldron"',
        "color = Color(0.2, 0.7, 0.1, 1.0)",
        "dot_enabled = true",
        "dot_total_damage = 50.0",
        "dot_tick_interval = 1.0",
        "dot_duration = 6.0",
        'dot_effect_type = "poison"',
        'dot_source_id = "plague_cauldron"',
        "dot_in_addition_to_hit = false",
        "footprint_size_class = 0",
        'size_class = "LARGE"',
        'role_tags = Array[String](["DPS", "ARTILLERY"])',
        'balance_status = "UNTESTED"',
    ],
)

wbd(
    "barracks_fortress.tres",
    34,
    [
        'building_id = "barracks_fortress"',
        "building_type = 34",
        'display_name = "Barracks Fortress"',
        "gold_cost = 320",
        "material_cost = 8",
        "upgrade_gold_cost = 192",
        "upgrade_material_cost = 5",
        "damage = 0.0",
        "upgraded_damage = 0.0",
        "fire_rate = 0.0",
        "attack_range = 0.0",
        "upgraded_range = 0.0",
        "damage_type = 0",
        "targets_air = false",
        "targets_ground = true",
        "is_locked = true",
        'unlock_research_id = "unlock_barracks_fortress"',
        "color = Color(0.7, 0.6, 0.3, 1.0)",
        "is_summoner = true",
        "summon_squad_size = 4",
        'summon_leader_data_path = "res://resources/ally_data/knight_captain.tres"',
        'summon_follower_data_path = "res://resources/ally_data/militia_archer.tres"',
        "summon_cooldown = 25.0",
        'summon_respawn_type = "recurring"',
        "summon_respawn_delay = 12.0",
        "summon_is_blocker = true",
        "footprint_size_class = 0",
        'size_class = "LARGE"',
        'role_tags = Array[String](["SUMMONER", "BLOCKER"])',
        'balance_status = "UNTESTED"',
    ],
    with_proj=False,
)

wbd(
    "citadel_aura.tres",
    35,
    [
        'building_id = "citadel_aura"',
        "building_type = 35",
        'display_name = "Citadel Aura"',
        "gold_cost = 350",
        "material_cost = 9",
        "damage = 0.0",
        "fire_rate = 0.0",
        "attack_range = 0.0",
        "upgraded_range = 0.0",
        "damage_type = 0",
        "targets_air = false",
        "targets_ground = true",
        "is_locked = true",
        'unlock_research_id = "unlock_citadel_aura"',
        "color = Color(1.0, 0.9, 0.3, 1.0)",
        "is_aura = true",
        'aura_category = "damage_flat"',
        "aura_radius = 18.0",
        'aura_effect_type = "damage_pct"',
        "aura_effect_value = 0.20",
        "footprint_size_class = 0",
        'size_class = "LARGE"',
        'role_tags = Array[String](["AURA", "SUPPORT"])',
        'balance_status = "UNTESTED"',
    ],
    with_proj=False,
)

# Fix ember_vent unlock - should not gate on frost_pinger; prompt says no lock for tier1 optional
# User table didn't list is_locked for ember - set unlock empty
# Patch ember_vent unlock_research_id to ""
print("Patch ember_vent unlock")
p = BD / "ember_vent.tres"
text = p.read_text()
text = text.replace('unlock_research_id = "unlock_frost_pinger"', 'unlock_research_id = ""')
p.write_text(text)

print("Generated buildings:", len(list(BD.glob("*.tres"))))
